### PR TITLE
Fix issues #58 & #63

### PR DESCRIPTION
**Pull request by aniruth37**
+ Fix issue https://github.com/package-url/packageurl-js/issues/58 - Incorrect parsing of PURLs beginning with `pkg://`
+ Fix issue https://github.com/package-url/packageurl-js/issues/63 - Incorrect parsing of PURL with leading '/' in namespace

Fix Description
+ strip /, // and /// as possible in pkg:/ or pkg:// or pkg:/// before passing into URL constructor
+ filter for non-empty items in `namespaceComponents`

### CODE REVIEW

**Comment by aniruth37** [comment]
@steven-esser
Please review this

**Comment by aniruth37** [comment]
@matt-phylum please review this

**Comment by aniruth37** [comment]
@pombredanne, @steven-esser 
Can you please review this PR

**Comment by jdalton** [comment]
I cannot reproduce #58 on master branch. 
```js
PackageURL.fromString('pkg://maven/org.apache.commons/io')
```
outputs
```js
{
  "type": "maven",
  "name": "io",
  "namespace": "org.apache.commons",
  "version": null,
  "qualifiers": null,
  "subpath": null
}
```

**Comment by matt-phylum** [comment]
Are you sure? That is not the behavior I get on the master branch (commit aa6d185251e3ec4e6fbc80489374c5fede9ccca1).

```
> PackageURL.fromString('pkg://maven/org.apache.commons/io')
PackageURL {
  type: 'maven',
  name: 'io',
  namespace: null,
  version: null,
  qualifiers: null,
  subpath: null
}
```

**Comment by jdalton** [comment]
Ah, my bad!

**Comment by jdalton** [comment]
Closing as covered by https://github.com/package-url/packageurl-js/pull/71

**Pull request closed without merging**
