### PR TITLE
Splitting purl remainder from right on '@' to extract version

### PR DESCRIPTION
**Pull request by Moullisha**
NPM purls contain namespaces starting with @ 
pkg:npm/@aws-crypto/crc32@3.0.0

### CODE REVIEW

**Comment by Moullisha** [comment]
Fix for issue #64 
@steven-esser @matt-phylum Please review!

**Comment by matt-phylum** [comment]
`pkg:npm/@aws-crypto/crc32@3.0.0` is technically an invalid PURL that most implementations should be able to handle anyway. The spec says "the '@' version separator must be encoded as %40 elsewhere". The correct PURL is `pkg:npm/%40aws-crypto/crc32@3.0.0`, even if it looks ugly.

However, this PR does fix a spec conformance problem. The spec also says "Split the remainder once from right on '@'", which is not what the previous code was doing.

**Comment by Moullisha** [comment]
@matt-phylum  The purl string **pkg:npm/@aws-crypto/crc32@3.0.0** was being accurately parsed using the python version of the module but js version was throwing error. But as you mentioned the python version does extract the version by splitting from the right on '@' (as required by the purl spec), thus the purl passed even without being percent-encoded.

**Comment by matt-phylum** [comment]
Yeah I think this is the right thing to do, even if the `%` was supposed to be escaped.

**Comment by Moullisha** [comment]
@matt-phylum If everything looks good, can you approve this PR?

**Comment by matt-phylum** [comment]
I'm not a maintainer on this project so my approval doesn't mean anything.

**Review by aniruth37 — APPROVED** [review]

**Comment by jdalton** [comment]
Closing as covered by https://github.com/package-url/packageurl-js/pull/71

**Comment by jdalton** [comment]
[v2.0.0](https://www.npmjs.com/package/packageurl-js/v/2.0.0) has been published 🎉

**Pull request closed without merging**
