### PR TITLE
Update npm deps

### PR DESCRIPTION
**Pull request by smorimoto**
This PR will be mergeable after merging #41. I'll take care of it because it probably needs a rebase.

### CODE REVIEW

**Comment by steven-esser** [comment]
@smorimoto https://github.com/package-url/packageurl-js/pull/41 was merged; once you rebase this PR, ill merge it and cut a new release with your additions/updates. 

Thanks for the contributions!

**Comment by smorimoto** [comment]
@steven-esser We were working at a pretty good moment even though there is the time difference 😄
I did it! Thank you for your quick confirmation!

**Review by steven-esser — APPROVED** [review]

**Comment by steven-esser** [comment]
v1.0.2 published with your changes: https://www.npmjs.com/package/packageurl-js/v/1.0.2

Thanks again!

**Comment by smorimoto** [comment]
Thank you so much!

**Pull request merged**
