### PR TITLE
fix: encoding of special chars when encoding to string

### PR DESCRIPTION
**Pull request by jkowalleck**
- [x] tests for proper encoding when `toString()` is called
- [x] fixed some encoding issues

### CODE REVIEW

**Comment by jkowalleck** [comment]
@steven-esser could you review?

**Review by steven-esser — DISMISSED** [review]
@jkowalleck This looks great. Thank you for your contribution!

**Review by steven-esser — APPROVED** [review]

**Comment by steven-esser** [comment]
@jkowalleck v1.0.1 released to npm with your fixes: https://www.npmjs.com/package/packageurl-js/v/1.0.1

Thanks again!

**Comment by anuccio1** [comment]
Just a heads up that this was actually a breaking change for my team. We aren't blocked per-say, just now locked into version 1.0.0.

Example Failing test:

```
AssertionError: expected 'pkg:maven/org.wso2.carbon.identity.fr…' to equal 'pkg:maven/org.wso2.carbon.identity.fr…'
      + expected - actual

      -pkg:maven/org.wso2.carbon.identity.framework/org.wso2.carbon.identity.user.profile.ui@5.12.21?repository_url=https%3A//maven.wso2.org/nexus/content/groups/wso2-public
      +pkg:maven/org.wso2.carbon.identity.framework/org.wso2.carbon.identity.user.profile.ui@5.12.21?repository_url=https://maven.wso2.org/nexus/content/groups/wso2-public
```

Perhaps we can add in an option to **not** encode ?

**Comment by jkowalleck** [comment]
https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst#rules-for-each-purl-component
-> section "qualifiers"

> A value must be a percent-encoded string

**Pull request merged**
